---
- name: Install EPEL repository
  yum:
    name: 'epel-release'
    state: latest

- name: Install nginx
  yum:
    name: nginx
    state: latest
  notify: start nginx

- name: Create website homedir
  file:
    path: /var/www/{{ nginx_host }}
    state: directory
    owner: root
    group: root

- name: Create config file for website
  template:
    src: templates/nginx.cnf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx

- name : Create index.html for website
  template:
    src: templates/index.html.j2
    dest: /var/www/{{ nginx_host }}/index.html

- name: Sets Up PHP Info Page
  template:
    src: "templates/info.php.j2"
    dest: "/var/www/{{ nginx_host }}/info.php"


