- name: Install remi repo
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Enable the correct Remi package to get PHP 7.4 installed
  command: yum-config-manager --enable remi-php74

- name: Install PHP
  yum:
    name: ['php', 'php-mysqlnd', 'php-fpm']

# - name: Config www.conf
#   template:
#     src: templates/www.conf.j2
#     dest: /etc/php-fpm.d/www.conf
#   notify: restart php-fpm